### PR TITLE
#162115570 add landing page with login and sign up links

### PR DESCRIPTION
**Pull request by larryTheGeek**
__what does this PR do?__

This PR adds a landing page that gives a brief description of the iReporter app

__Description of task to be completed?__

  Have a simple landing page with a brief description of the app and links to;
- user login
- admin login
- user sign up

__How should this be manually tested?__ 
 
after cloning the repo open the UI folder and open the index.html file using a browser preferably chrome.

__Any background context you want to provide?__
The design is a mock-up and does not have any functionality yet

__Relevant screenshots__

home

### CODE REVIEW

**Comment by xcixor** [comment]
looks good, nice text contrast with background

**Comment by antonnifo** [comment]
This design looks great

**Comment by macymuhia** [comment]
Looks amazing, wow

**Comment by kirega** [comment]
I like the design and the layouts.

**Comment by dmukuna** [comment]
Looking good

**Comment by Benkimeric** [comment]
Nice desgin

**Pull request merged**
